title: Andrii Aheiev's personal site
email: a.ageyev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaheiev.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aaheiev

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-pug

sass:
  load_paths:
    - _sass
    - node_modules

#include:
#  - node_modules

exclude:
  - .sass-cache/
  - .idea/
  - .jekyll-cache/
  - node_modules
  - gemfiles/
  - Gemfile
  - Gemfile.lock
